#!/usr/bin/perl
#List *.tex and *.m files on the command line to get Makefile dependencies
foreach $fn (@ARGV) {
    open(F, "<$fn");
    if ($fn =~ /\.tex$/) {
	my $dep;
	while (<F>) {
	    if (/\\includegraphics\*?(?:\[\S+\]){0,2}\{([\w\.-]+.eps)\}/) {
		$dep .= ' ' if $dep;
		$dep .= $1;
	    }
	}
	print "$fn: $dep\n\n" if $dep;
    } elsif ($fn =~ /\.m$/) {
	my $cmd = $`;
	my $prod;
	my $dep = $fn;
	while (<F>) {
	    # handle continuation lines
	    while (s/\.\.\.\s*$//) {
		$_ .= <F>;
	    }
	    if (/^\s*(imwrite|saveas)\(.*?'([\w\.%-]+)\'.*?(,\s*\'\w+\'\s*)?\);?\s*$/) {
		$prod .= ' ' if $prod;
		$prod .= $2;
	    }
            if (/^\s*load\s+([\w\.%-\@]+)\s*(;.*)?\s*$/) {
                $dep .= " $1"
            }
	}
	if ($prod && !$matlab) {
	    print "MATLAB=matlab -nosplash\n\n";
	    $matlab = 1;
	}
	print "$prod: $dep\n\techo $cmd | \$(MATLAB)\n\n" if $prod;
    } else {
	die("Unknown file type of '$fn'");
    }
    close(F);
}
